chore: updating api version for plug & play release
Azure/azure-iot-sdk-node pull request #896
Opened 2020-09-23 19:55 UTC by jebrando

# Checklist
- [ ] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-node/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.

# Reference/Link to the issue solved with this PR (if any)

# Description of the problem

# Description of the solution

2020-09-23 20:01 UTC, anthonyvercolano commented on service/src/twin.ts
>    /**
How the heck did I miss this.

2020-09-23 20:03 UTC, anthonyvercolano commented on service/test/_twin_test.js
> +      var fakeModelId = 'modelId';
>var fakeModelId = 'modelId'; [](start = 6, length = 28)

Shouldn't this be on regular twin also?

2020-09-23 20:05 UTC, YoDaMa commented on service/src/twin.ts
>    /**
genius

2020-09-23 20:05 UTC, anthonyvercolano commented on service/test/_twin_test.js
> +      twin.modelId = fakeModelId;
>twin.modelId = fakeModelId; [](start = 6, length = 27)

I don't see any assertion based on this.

2020-09-24 00:49 UTC, anthonyvercolano approved these changes
:shipit:

2020-09-25 19:57 UTC, zolvarga commented
>  */

Rename this file to "_digital_twin_client_test.js"

---
Refers to: service/test/_digital_twin_service_client_test.js:6 in 1ccaefb. [](commit_id = 1ccaefb988ff35dc3a2e89f2518d3bcde887ef43, deletion_comment = False)

2020-09-25 19:58 UTC, zolvarga commented on service/samples/typescript/get_digital_twins.ts
> +// - create a Digital Twin Service Client using the DigitalTwinClient constructor
>Digital Twin Service [](start = 14, length = 20)

Rename those too

2020-09-25 19:59 UTC, zolvarga commented on service/samples/typescript/invoke_command.ts
> +// - create a Digital Twin Service Client using the DigitalTwinClient constructor
>Digital Twin Service Clien [](start = 14, length = 26)

Rename...

2020-09-25 19:59 UTC, zolvarga commented on service/samples/typescript/invoke_component_command.ts
> +// - create a Digital Twin Service Client using the DigitalTwinClient constructor
>Digital Twin Service Client [](start = 14, length = 27)

Rename

2020-09-25 20:00 UTC, zolvarga commented on service/samples/javascript/get_digital_twin.js
> +// - create a Digital Twin Service Client using the DigitalTwinClient constructor
>Digital Twin Service Client [](start = 14, length = 27)

Rename

2020-09-25 20:00 UTC, zolvarga commented on service/samples/javascript/invoke_command.js
> +// - create a Digital Twin Service Client using the DigitalTwinClient constructor
>Digital Twin Service Client [](start = 14, length = 27)

Rename

2020-09-25 20:00 UTC, zolvarga commented on service/samples/javascript/invoke_component_command.js
> +// - create a Digital Twin Service Client using the DigitalTwinClient constructor
>Digital Twin Service Client [](start = 14, length = 27)

Rename

2020-09-25 20:00 UTC, zolvarga commented on service/samples/javascript/update_digital_twin.js
> +// - create a Digital Twin Service Client using the DigitalTwinClient constructor
>Digital Twin Service Client [](start = 14, length = 27)

Rename

2020-09-25 20:00 UTC, zolvarga commented on service/devdoc/service_client_requirements.md
>  # Digital Twin Service Client requirements
>Digital Twin Service Client [](start = 2, length = 27)

Rename

2020-09-25 20:06 UTC, anthonyvercolano commented on service/test/_twin_test.js
> +      var fakeTwin = { deviceId: 'fakeDeviceId' };
>ar fakeTwin = { deviceId: 'fakeDeviceId' }; [](start = 7, length = 43)

This can't be right.

2020-09-25 20:06 UTC, anthonyvercolano requested changes
:clock1:

2020-09-25 20:39 UTC, jebrando commented on service/samples/typescript/invoke_command.ts
> +// - create a Digital Twin Service Client using the DigitalTwinClient constructor
Done

2020-09-25 20:39 UTC, jebrando commented on service/samples/typescript/get_digital_twins.ts
> +// - create a Digital Twin Service Client using the DigitalTwinClient constructor
Done

2020-09-25 20:40 UTC, zolvarga approved these changes
:shipit:

2020-09-25 20:41 UTC, jebrando commented on service/samples/javascript/update_digital_twin.js
> +// - create a Digital Twin Service Client using the DigitalTwinClient constructor
Done

2020-09-25 20:41 UTC, jebrando commented on service/devdoc/service_client_requirements.md
>  # Digital Twin Service Client requirements
Done

2020-09-25 20:42 UTC, jebrando commented on service/test/_twin_test.js
> +      var fakeTwin = { deviceId: 'fakeDeviceId' };
You sir are correct.

2020-09-25 23:51 UTC, anthonyvercolano approved these changes
:shipit:

2020-09-28 15:45 UTC, merged