fix(azure-iot-provisioning-device): change RegistrationClient to expose promisified version of API
Azure/azure-iot-sdk-node pull request #928
Opened 2021-02-04 20:09 UTC by vishnureddy17

fixes issue #927

2021-02-04 20:58 UTC, YoDaMa approved these changes

2021-02-04 20:59 UTC, YoDaMa requested changes
I think that this is a good change, can we verify that people will not be broken by this change?

2021-02-04 22:24 UTC, vishnureddy17 commented
@YoDaMa The callback versions of the functions appear to be working as normal with the change.

2021-02-05 00:03 UTC, YoDaMa approved these changes

2021-02-05 00:03 UTC, YoDaMa commented
lgtm

2021-02-05 00:31 UTC, merged